[package]
name = "vault-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.21"
sha2 = "0.10"
typenum = "1.17.0"
rpassword = "7.2"